# Generated by Django 5.1.5 on 2025-03-04 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyinformation',
            name='destination',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Please only enter letters.')]),
        ),
    ]
