# Generated by Django 5.1.6 on 2025-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_journeyinformation_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_city', models.CharField(max_length=64)),
                ('activity_image', models.CharField(blank=True, max_length=64)),
                ('activity_title', models.CharField(max_length=64)),
                ('activity_price', models.CharField(max_length=8)),
                ('activity_desc', models.CharField(max_length=256)),
                ('activity_short_desc', models.CharField(max_length=64)),
                ('activity_type', models.CharField(max_length=16)),
                ('activity_group_size', models.CharField(max_length=16)),
                ('activity_age', models.CharField(max_length=16)),
                ('activity_duration', models.CharField(max_length=16)),
                ('activity_popularity', models.CharField(max_length=16)),
                ('activity_accessibility', models.CharField(max_length=16)),
            ],
        ),
    ]
