# Generated by Django 5.1.6 on 2025-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_accessibility',
            field=models.CharField(max_length=32),
        ),
    ]
