# Generated by Django 5.1.6 on 2025-03-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_activity_activity_accessibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_accessibility',
            new_name='accessibility',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_group_size',
            new_name='group_size',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_popularity',
            new_name='popularity',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_short_desc',
            new_name='short_desc',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_title',
            new_name='title',
        ),
    ]
