# Generated by Django 5.1.6 on 2025-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_activity_accessibility_activity_accessibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=32)),
                ('activity_ids', models.JSONField(default=list)),
                ('city', models.CharField(max_length=32)),
                ('cost', models.CharField(max_length=16)),
                ('departure', models.CharField(max_length=16)),
                ('arrival', models.CharField(max_length=16)),
            ],
        ),
    ]
