# Generated by Django 5.1.6 on 2025-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_journeyinformation_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
