# Generated by Django 5.1.6 on 2025-03-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_activity_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='name',
        ),
    ]
