# Generated by Django 5.1.6 on 2025-03-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_destination_journeyinformation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='country',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
